/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppWorkoutRouteImport } from './routes/_app.workout'
import { Route as AppExerciseIdRouteImport } from './routes/_app.exercise.$id'
import { Route as AppHistoryIndexRouteImport } from './routes/_app.history.index'
import { Route as AppHistoryIdRouteImport } from './routes/_app.history.$id'
import { Route as AppHistoryTimelineRouteImport } from './routes/_app.history.timeline'
import { Route as AppSettingsDatabaseRouteImport } from './routes/_app.settings_.database'
import { Route as AppSettingsRestTimesRouteImport } from './routes/_app.settings_.rest-times'
import { Route as AppSettingsRestTimesExerciseIdRouteImport } from './routes/_app.settings_.rest-times_.$exerciseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkoutRoute = AppWorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => AppRoute,
} as any)
const AppExerciseIdRoute = AppExerciseIdRouteImport.update({
  id: '/exercise/$id',
  path: '/exercise/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryIndexRoute = AppHistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHistoryRoute,
} as any)
const AppHistoryIdRoute = AppHistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppHistoryRoute,
} as any)
const AppHistoryTimelineRoute = AppHistoryTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppHistoryRoute,
} as any)
const AppSettingsDatabaseRoute = AppSettingsDatabaseRouteImport.update({
  id: '/settings_/database',
  path: '/settings/database',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRestTimesRoute = AppSettingsRestTimesRouteImport.update({
  id: '/settings_/rest-times',
  path: '/settings/rest-times',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRestTimesExerciseIdRoute =
  AppSettingsRestTimesExerciseIdRouteImport.update({
    id: '/settings_/rest-times_/$exerciseId',
    path: '/settings/rest-times/$exerciseId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof AppHistoryRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/workout': typeof AppWorkoutRoute
  '/exercise/$id': typeof AppExerciseIdRoute
  '/history/$id': typeof AppHistoryIdRoute
  '/history/timeline': typeof AppHistoryTimelineRoute
  '/settings/database': typeof AppSettingsDatabaseRoute
  '/settings/rest-times': typeof AppSettingsRestTimesRoute
  '/history/': typeof AppHistoryIndexRoute
  '/settings/rest-times/$exerciseId': typeof AppSettingsRestTimesExerciseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/workout': typeof AppWorkoutRoute
  '/exercise/$id': typeof AppExerciseIdRoute
  '/history/$id': typeof AppHistoryIdRoute
  '/history/timeline': typeof AppHistoryTimelineRoute
  '/settings/database': typeof AppSettingsDatabaseRoute
  '/settings/rest-times': typeof AppSettingsRestTimesRoute
  '/history': typeof AppHistoryIndexRoute
  '/settings/rest-times/$exerciseId': typeof AppSettingsRestTimesExerciseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/history': typeof AppHistoryRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/workout': typeof AppWorkoutRoute
  '/_app/exercise/$id': typeof AppExerciseIdRoute
  '/_app/history/$id': typeof AppHistoryIdRoute
  '/_app/history/timeline': typeof AppHistoryTimelineRoute
  '/_app/settings_/database': typeof AppSettingsDatabaseRoute
  '/_app/settings_/rest-times': typeof AppSettingsRestTimesRoute
  '/_app/history/': typeof AppHistoryIndexRoute
  '/_app/settings_/rest-times_/$exerciseId': typeof AppSettingsRestTimesExerciseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/profile'
    | '/settings'
    | '/workout'
    | '/exercise/$id'
    | '/history/$id'
    | '/history/timeline'
    | '/settings/database'
    | '/settings/rest-times'
    | '/history/'
    | '/settings/rest-times/$exerciseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/settings'
    | '/workout'
    | '/exercise/$id'
    | '/history/$id'
    | '/history/timeline'
    | '/settings/database'
    | '/settings/rest-times'
    | '/history'
    | '/settings/rest-times/$exerciseId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/history'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/workout'
    | '/_app/exercise/$id'
    | '/_app/history/$id'
    | '/_app/history/timeline'
    | '/_app/settings_/database'
    | '/_app/settings_/rest-times'
    | '/_app/history/'
    | '/_app/settings_/rest-times_/$exerciseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workout': {
      id: '/_app/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof AppWorkoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercise/$id': {
      id: '/_app/exercise/$id'
      path: '/exercise/$id'
      fullPath: '/exercise/$id'
      preLoaderRoute: typeof AppExerciseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history/': {
      id: '/_app/history/'
      path: '/'
      fullPath: '/history/'
      preLoaderRoute: typeof AppHistoryIndexRouteImport
      parentRoute: typeof AppHistoryRoute
    }
    '/_app/history/$id': {
      id: '/_app/history/$id'
      path: '/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof AppHistoryIdRouteImport
      parentRoute: typeof AppHistoryRoute
    }
    '/_app/history/timeline': {
      id: '/_app/history/timeline'
      path: '/timeline'
      fullPath: '/history/timeline'
      preLoaderRoute: typeof AppHistoryTimelineRouteImport
      parentRoute: typeof AppHistoryRoute
    }
    '/_app/settings_/database': {
      id: '/_app/settings_/database'
      path: '/settings/database'
      fullPath: '/settings/database'
      preLoaderRoute: typeof AppSettingsDatabaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings_/rest-times': {
      id: '/_app/settings_/rest-times'
      path: '/settings/rest-times'
      fullPath: '/settings/rest-times'
      preLoaderRoute: typeof AppSettingsRestTimesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings_/rest-times_/$exerciseId': {
      id: '/_app/settings_/rest-times_/$exerciseId'
      path: '/settings/rest-times/$exerciseId'
      fullPath: '/settings/rest-times/$exerciseId'
      preLoaderRoute: typeof AppSettingsRestTimesExerciseIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppHistoryRouteChildren {
  AppHistoryIdRoute: typeof AppHistoryIdRoute
  AppHistoryTimelineRoute: typeof AppHistoryTimelineRoute
  AppHistoryIndexRoute: typeof AppHistoryIndexRoute
}

const AppHistoryRouteChildren: AppHistoryRouteChildren = {
  AppHistoryIdRoute: AppHistoryIdRoute,
  AppHistoryTimelineRoute: AppHistoryTimelineRoute,
  AppHistoryIndexRoute: AppHistoryIndexRoute,
}

const AppHistoryRouteWithChildren = AppHistoryRoute._addFileChildren(
  AppHistoryRouteChildren,
)

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorkoutRoute: typeof AppWorkoutRoute
  AppExerciseIdRoute: typeof AppExerciseIdRoute
  AppSettingsDatabaseRoute: typeof AppSettingsDatabaseRoute
  AppSettingsRestTimesRoute: typeof AppSettingsRestTimesRoute
  AppSettingsRestTimesExerciseIdRoute: typeof AppSettingsRestTimesExerciseIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWorkoutRoute: AppWorkoutRoute,
  AppExerciseIdRoute: AppExerciseIdRoute,
  AppSettingsDatabaseRoute: AppSettingsDatabaseRoute,
  AppSettingsRestTimesRoute: AppSettingsRestTimesRoute,
  AppSettingsRestTimesExerciseIdRoute: AppSettingsRestTimesExerciseIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
